#
# requires the following gitlab secret variables
# - DOCKER_REGISTRY_USERNAME
# - DOCKER_REGISTRY_PASSWORD
# - DOCKER_REGISTRY_EMAIL
#
# Adjust "DOCKER_REGISTRY_REPOSITORY" variable (below) to be the name of the repository in the specified registry.
#
#

image: maven:3.5.3-jdk-8

before_script:
  - export REVISION=$(date +%Y%m%d.%H%M).$CI_COMMIT_REF_SLUG.$(echo $CI_COMMIT_SHA | cut -c1-7)

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dskip.cloudbees-estatio-repositories -Dskip.sonatype-snapshots -Dskip.apache-snapshots"
  DOCKER_REGISTRY_ID: "docker-hub"
  DOCKER_REGISTRY_URL: "https://index.docker.io/v1/"
  DOCKER_REGISTRY_REPOSITORY: "simpleapp"

stages:
  - build-package-push

build-package-push:
  stage: build-package-push
  script:
    - echo "REVISION=$REVISION"
    - >
      mvn $MAVEN_CLI_OPTS \
          clean install \
          -Drevision=$REVISION \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_REPOSITORY
    - >
      mvn $MAVEN_CLI_OPTS \
          docker:push@push-image-tagged \
          -pl webapp \
          -Drevision=$REVISION \
          -DskipTests \
          -Dskip.isis-swagger \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_REPOSITORY \
          -Ddocker-plugin.serverId=$DOCKER_REGISTRY_ID \
          -Ddocker.registryUrl=$DOCKER_REGISTRY_URL

